name: workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  workflow:
    uses: foremanmining/workflows/.github/workflows/java.yml@main
    with:
      result-folder: './'
      gcs-bucket: guardrail-releases
      java: 8
    secrets: inherit